### ISSUE TITLE
requirements.txt ?

### ISSUE THREAD

**Issue by rastarr** [jmfrick1/RedditBotProject#1]
I'm interested in your project but don't see any requirements.txt
Is this project currently active and able to be used?
Thanks

**Comment by jmfrick1** [comment]
I have to make my way back around to this project, this project is very incomplete and missing bunch of code but has the basic structure

**Comment by jmfrick1** [comment]
It's fixed for now. not sure how well it actually works but it opens. check out the releases for the exe or build it
